"""initial tables

Revision ID: 1e8eec0ddec7
Revises: 
Create Date: 2026-03-06 02:25:34.756697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8eec0ddec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('primary_type', sa.String(), nullable=True),
    sa.Column('types', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enriched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_enriched'), ['enriched'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_place_id'), ['place_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_businesses_status'), ['status'], unique=False)

    op.create_table('intel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('company_summary', sa.Text(), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('estimated_size', sa.Text(), nullable=True),
    sa.Column('target_customers', sa.Text(), nullable=True),
    sa.Column('key_contacts', sa.Text(), nullable=True),
    sa.Column('technologies_used', sa.Text(), nullable=True),
    sa.Column('recent_news', sa.Text(), nullable=True),
    sa.Column('potential_pain_points', sa.Text(), nullable=True),
    sa.Column('outreach_angle', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_business_id'))

    op.drop_table('notes')
    op.drop_table('intel')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_status'))
        batch_op.drop_index(batch_op.f('ix_businesses_place_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_enriched'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
