"""
Accounting & Bookkeeping Firm searcher profile.

Generated by generator.py, then reviewed and promoted. The searcher sells
outsourced bookkeeping, tax, payroll, and fractional controller/CFO services;
its buyer is whoever controls the money -- the owner at small shops, the
finance lead (CFO / controller / bookkeeper) at larger ones.

Contrast with gc.py: this profile selects the FINANCE roles the GC ignores from
the same shared inventories, skips the large in-house-finance / procurement
segments (corporate offices, hospitals, higher ed, K-12, government, retail
chains), and DOES target trade_contractor -- the segment the GC skips.

Review note from generation: the hospitality_hotel play carries `controller`
as a probe_role because that inventory (GC-shaped) doesn't list finance roles a
hotel actually has. If this probe keeps recurring across profiles, promote
`controller` into hospitality_hotel's inventory in target_segments.py.
"""

from searcher_profiles.base import SearcherProfile, SegmentPlay

_RATIONALE = ("Outsourced bookkeeping, tax, and controller work; the owner or "
             "finance lead is the buyer.")
_TACTICS = [
    '"{company}" "{city}" owner OR "chief financial officer" OR controller',
    '"{company}" linkedin "{city}" bookkeeper OR controller OR "office manager"',
]


def _p(seg_id, ranked, probe=None):
    return SegmentPlay(
        segment_id=seg_id, ranked_roles=ranked, probe_roles=probe or [],
        sales_rationale=_RATIONALE, search_tactics=_TACTICS,
    )


ACCOUNTANT_PROFILE = SearcherProfile(
    searcher_id="accountant",
    display_name="Accounting & Bookkeeping Firm",
    description=(
        "A small accounting and bookkeeping firm in metro Atlanta selling "
        "monthly bookkeeping, tax prep, payroll, and fractional controller/CFO "
        "services to local businesses. The buyer is whoever owns the money: the "
        "owner at small shops, the finance lead (CFO/controller/bookkeeper) at "
        "larger ones."
    ),
    plays={
        "professional_services_office": _p("professional_services_office",
            ["owner", "managing_partner", "cfo", "controller", "bookkeeper", "office_manager", "administrator"]),
        "manufacturing_industrial": _p("manufacturing_industrial",
            ["cfo", "controller", "owner", "general_manager", "coo"]),
        "trade_services_small_business": _p("trade_services_small_business",
            ["owner", "founder", "bookkeeper", "office_manager", "general_manager"]),
        "wellness_studio": _p("wellness_studio",
            ["owner", "franchisee", "bookkeeper", "general_manager", "studio_manager"]),
        "independent_small_business": _p("independent_small_business",
            ["owner", "founder", "bookkeeper", "president", "office_manager"]),
        "healthcare_practice": _p("healthcare_practice",
            ["owner", "practice_manager", "office_manager", "bookkeeper", "managing_physician"]),
        "childcare_camp": _p("childcare_camp",
            ["owner", "franchisee", "bookkeeper", "center_director"]),
        "campground_rv": _p("campground_rv",
            ["owner", "general_manager", "property_manager"]),
        "commercial_property": _p("commercial_property",
            ["owner", "asset_manager", "property_manager"]),
        "religious_nonprofit": _p("religious_nonprofit",
            ["administrator", "bookkeeper", "executive_director", "executive_pastor"]),
        "auto_dealership": _p("auto_dealership",
            ["cfo", "owner", "dealer_principal", "general_manager"]),
        "auto_service": _p("auto_service",
            ["owner", "franchisee", "general_manager", "regional_manager"]),
        "fitness_recreation": _p("fitness_recreation",
            ["owner", "franchisee", "general_manager"]),
        "entertainment_venue": _p("entertainment_venue",
            ["owner", "general_manager", "executive_director", "venue_manager"]),
        "self_storage": _p("self_storage",
            ["owner", "regional_manager"]),
        "trade_contractor": _p("trade_contractor",
            ["owner", "bookkeeper", "controller", "office_manager", "general_manager"]),
        "hospitality_hotel": _p("hospitality_hotel",
            ["owner", "controller", "franchisee", "general_manager", "asset_manager"]),
    },
)

# Generator's default export name is PROFILE; keep it as an alias.
PROFILE = ACCOUNTANT_PROFILE
