"""
Business Law Firm searcher profile.

Generated by generator.py, then reviewed and promoted. The searcher provides
outside counsel -- contracts, entity formation, employment, commercial leases,
disputes, compliance -- to local businesses. Its buyer is whoever authorizes
legal work: the owner/executive, or in-house counsel/HR where present.

Contrast: where the accountant selects finance roles and the GC selects
facilities roles from the same shared inventories, the attorney selects the
legal/executive decision-makers. It skips the large in-house-legal / panel-
counsel segments (corporate offices, hospitals, higher ed, K-12, government,
retail chains) and DOES target trade_contractor.

Review note: the manufacturing_industrial play carries `general_counsel` as a
probe_role because that inventory doesn't list it, though larger manufacturers
have in-house counsel. If this probe recurs across profiles, promote
`general_counsel` into manufacturing_industrial's inventory.
"""

from searcher_profiles.base import SearcherProfile, SegmentPlay

_RATIONALE = ("Outside counsel for contracts, entity, employment, and disputes; "
             "the owner/executive or in-house counsel is the buyer.")
_TACTICS = [
    '"{company}" "{city}" owner OR president OR "general counsel"',
    '"{company}" linkedin "{city}" "general counsel" OR owner OR "managing partner"',
]


def _p(seg_id, ranked, probe=None):
    return SegmentPlay(
        segment_id=seg_id, ranked_roles=ranked, probe_roles=probe or [],
        sales_rationale=_RATIONALE, search_tactics=_TACTICS,
    )


ATTORNEY_PROFILE = SearcherProfile(
    searcher_id="attorney",
    display_name="Business Law Firm",
    description=(
        "A small business/commercial law firm in metro Atlanta providing "
        "outside counsel to local businesses: contracts, entity formation, "
        "employment law, commercial leases, disputes, and compliance."
    ),
    plays={
        "professional_services_office": _p("professional_services_office",
            ["owner","managing_partner","general_counsel","president","coo","hr_director","administrator"]),
        "manufacturing_industrial": _p("manufacturing_industrial",
            ["owner","general_counsel","coo","general_manager","hr_director","ehs_manager"]),
        "trade_services_small_business": _p("trade_services_small_business",
            ["owner","founder","general_manager"]),
        "wellness_studio": _p("wellness_studio",
            ["owner","franchisee","general_manager"]),
        "independent_small_business": _p("independent_small_business",
            ["owner","founder","president","operating_partner","general_manager"]),
        "healthcare_practice": _p("healthcare_practice",
            ["owner","managing_physician","ceo","practice_manager"]),
        "childcare_camp": _p("childcare_camp",
            ["owner","franchisee","center_director"]),
        "campground_rv": _p("campground_rv",
            ["owner","general_manager"]),
        "commercial_property": _p("commercial_property",
            ["owner","asset_manager","property_management_director","leasing_director"]),
        "religious_nonprofit": _p("religious_nonprofit",
            ["executive_director","executive_pastor","administrator","building_committee_chair"]),
        "auto_dealership": _p("auto_dealership",
            ["owner","dealer_principal","general_manager"]),
        "auto_service": _p("auto_service",
            ["owner","franchisee","general_manager","regional_manager"]),
        "fitness_recreation": _p("fitness_recreation",
            ["owner","franchisee","general_manager"]),
        "entertainment_venue": _p("entertainment_venue",
            ["owner","executive_director","general_manager","venue_manager"]),
        "self_storage": _p("self_storage",
            ["owner","regional_manager","real_estate_director"]),
        "trade_contractor": _p("trade_contractor",
            ["owner","president","general_manager","operations_director"]),
        "hospitality_hotel": _p("hospitality_hotel",
            ["owner","franchisee","general_manager","asset_manager"]),
    },
)

PROFILE = ATTORNEY_PROFILE
