"""
Executive Headshot Photographer searcher profile (Ric Mershon Photography).

Generated by generator.py, then reviewed and promoted. On-location executive and
corporate headshots for North Metro Atlanta tech/finance/law, plus an ongoing
"Image Continuity" program embedded in a client's onboarding and leadership-
refresh cycles.

Contrast with the others: where the GC picks facilities roles, the accountant
finance roles, and the attorney legal/executive roles, the photographer targets
whoever owns BRAND IMAGERY and NEW-HIRE ONBOARDING -- marketing/communications
and HR/people ops first, then the office manager and owners/partners. Now that
marketing_director/communications_director exist in the catalog, they lead the
professional and corporate plays (they're the true brand-imagery buyers).
"""

from searcher_profiles.base import SearcherProfile, SegmentPlay

_RATIONALE = ("Executive, leadership-team, and full-org headshots plus an "
             "ongoing image-continuity program tied to onboarding; the buyer "
             "owns brand imagery and new-hire onboarding.")
_TACTICS = [
    'site:{domain} team OR leadership OR staff OR "our people"',
    '"{company}" "{city}" "marketing" OR "communications" OR "human resources" OR "office manager"',
    '"{company}" linkedin "{city}"',
]


def _p(seg_id, ranked, probe=None):
    return SegmentPlay(
        segment_id=seg_id, ranked_roles=ranked, probe_roles=probe or [],
        sales_rationale=_RATIONALE, search_tactics=_TACTICS,
    )


PHOTOGRAPHER_PROFILE = SearcherProfile(
    searcher_id="photographer",
    display_name="Executive Headshot Photographer",
    description=(
        "An executive and corporate headshot photographer in North Metro "
        "Atlanta, on-location, focused on tech, finance, and law. Sells "
        "executive sessions, leadership-team and full-org headshot days, and an "
        "ongoing image-continuity program embedded in onboarding and "
        "leadership-refresh cycles."
    ),
    plays={
        "professional_services_office": _p("professional_services_office",
            ["marketing_director", "hr_director", "office_manager", "communications_director", "operations_director", "managing_partner", "owner", "administrator"]),
        "corporate_office": _p("corporate_office",
            ["marketing_director", "hr_director", "communications_director", "office_manager", "operations_director", "chief_administrative_officer", "coo"]),
        "healthcare_practice": _p("healthcare_practice",
            ["practice_manager", "owner", "managing_physician", "office_manager"]),
        "manufacturing_industrial": _p("manufacturing_industrial",
            ["marketing_director", "hr_director", "operations_director", "general_manager", "owner", "coo"]),
        "independent_small_business": _p("independent_small_business",
            ["owner", "founder", "president", "general_manager"]),
    },
)

PROFILE = PHOTOGRAPHER_PROFILE
